### ISSUE TITLE
Column Mode doesn't work

### ISSUE THREAD

**Issue by hongnod** [copperspice/diamond#21] opened 2022-03-14 03:04 UTC
v1.3.7 build 01/18/2022 on Windows10.press alt+C switch to column mode doesn't work.

**Comment by bgeller** [comment] 2022-03-14 23:25
I retested this exact version on Windows 10 and we are unable to reproduce any issues. Did you change the fonts so the column mode uses one which is mono spaced?  Under Settings, Fonts, you will see fields to select the "normal" and "columm" mode fonts. I use DejaVu Sans for normal and Courier for the column mode. 

Can you let us know what happened or what you expected to see?

**Comment by bgeller** [comment] 2022-05-17 02:51
Closing since we are unable to reproduce.  Re-open if you have further information.

**Closed as completed by bgeller** 2022-05-17 02:51 UTC
